version : '3.5'
services:
  call:
    image : caller
    container_name : callerapp
    ports :
      - 5010:5010
    networks : 
      - mynet

  sqr:
    image : sqrnum
    container_name : sqrapp
    ports :
      - 5020:5020
    networks :
      - mynet

  cube:
    image : cubenum
    container_name : cubeapp
    ports :
      - 5030:5030
    networks :
      - mynet

  sum:
    image : addnum
    container_name : addapp
    ports :
      - 5040:5040
    networks :
      - mynet

networks:
  mynet:
    name : mynetwork
    driver : bridge 

